namespace Uwizard {
    public struct Langs {
        public static string[][] texts = new string[][] {
#region ENGLISH_UWIZARD
            new string[] { // English
"Verified as Correct by SHA1" /* 0 */ , 
"Verified as Incorrect by SHA1" /* 1 */ , 
"No Key Entered" /* 2 */ , 
"No SHA1 Available" /* 3 */ , 
"The settings file is missing! Your settings and system keys are now lost." /* 4 */ , 
"Invalid Hex String" /* 5 */ , 
"Dowloading " /* 6 */ , 
"Reading " /* 7 */ , 
"Invalid Wii U disc Image. Perhaps you forgot to unzip the file?" /* 8 */ , 
"Searching game database..." /* 9 */ , 
"This game is not in the database. Please enter the name:" /* 10 */ , 
"Enter Game Name" /* 11 */ , 
"PAL: Europe" /* 12 */ , 
"NTSC: Japan" /* 13 */ , 
"PAL: Australia" /* 14 */ , 
"NTSC: North America" /* 15 */ , 
"Searching GameTDB for covers..." /* 16 */ , 
"Wii U Games|*.wud|All Files|*.*" /* 17 */ , 
"The disc title key is required to decrypt the data." /* 18 */ , 
"The common key is required to decrypt the data." /* 19 */ , 
"The disc title key is invalid." /* 20 */ , 
"The common key is invalid." /* 21 */ , 
"Select where to save the extracted files." /* 22 */ , 
"Error Extracting Files!" /* 23 */ , 
"version " /* 24 */ , 
"Uwizard has been successfully updated to version " /* 25 */ , 
"Uwizard has been updated to version {0}, but because of an error in the update process, some of your data may not be intact." /* 26 */ , 
"The game list is up to date." /* 27 */ , 
"{0} games added and {1} games updated from gametdb.com" /* 28 */ , 
"{0} game added and {1} games updated from gametdb.com" /* 29 */ , 
"{0} games added and {1} game updated from gametdb.com" /* 30 */ , 
"{0} game added and {1} game updated from gametdb.com" /* 31 */ , 
"Error downloading version information from wiiubrew.net. Update process canceled." /* 32 */ , 
"Corrupt version file at wiiubrew.net!" /* 33 */ , 
"ERROR" /* 34 */ , 
"There is a new version of Uwizard available. Do you want to update from {0} to {1} ?" /* 35 */ , 
"Uwizard is up to date!" /* 36 */ , 
"Are you sure you want to permanently delete all keys including title keys?" /* 37 */ , 
"All keys have been succesfully deleted!" /* 38 */ , 
"Are you sure you want to permanently delete all information about all games?" /* 39 */ , 
"You must time-travel into the future to use this feature! :)" /* 40 */ , 
"Decrypting contents..." /* 41 */ , 
"Finished decrypting contents." /* 42 */ , 
"Error decrypting contents!" /* 43 */ , 
"Opening output directory..." /* 44 */ , 
"Starting NUS Download. Please be patient!" /* 45 */ , 
"NUS Download Finished." /* 46 */ , 
"Download failed: " /* 47 */ , 
"Either this is not a valid Wii U Sound Stream, or the file is in use by another program." /* 48 */ , 
"Select where to look for sound files." /* 49 */ , 
"There are no compatible sound files in the selected directory!" /* 50 */ , 
"Error converting " /* 51 */ , 
"Select a directory that contains Wii U games to add to this list." /* 52 */ , 
"You have not saved your changes to the current Wii U game's information. This includes the name and the title key. Do you want to save these changes now?" /* 53 */ , 
"The common key is required to decrypt the data." /* 54 */ , 
"Type the name of the title to add." /* 55 */ , 
"WUD Manager" /* 56 */ , 
"NUS Downloader U" /* 57 */ , 
"Sound Manager" /* 58 */ , 
"Archive Manager" /* 59 */ , 
"Settings" /* 60 */ , 
"Show Game List" /* 61 */ , 
"Clear Folder List" /* 62 */ , 
"Add Folder" /* 63 */ , 
"Scrub Wii U Game" /* 64 */ , 
"Show Full Cover" /* 65 */ , 
"Save Game Information" /* 66 */ , 
"Extract Game Files" /* 67 */ , 
"Game Info" /* 68 */ , 
"Title Key" /* 69 */ , 
"Import" /* 70 */ , 
"Game Name" /* 71 */ , 
"Game ID" /* 72 */ , 
"Open Wii U Game" /* 73 */ , 
"Clear List" /* 74 */ , 
"Delete Title" /* 75 */ , 
"Add Title" /* 76 */ , 
"Version:" /* 77 */ , 
"Title ID:" /* 78 */ , 
"Decrypt Contents" /* 79 */ , 
"Open Folder" /* 80 */ , 
"Play Sound Stream" /* 81 */ , 
"Select Folder" /* 82 */ , 
"Sound Files in Selected Folder" /* 83 */ , 
"Decode a Wii U Sound Stream" /* 84 */ , 
"Decode Wii U Sound Streams to WAVs" /* 85 */ , 
"Decode Wii U Sound Stream to WAV" /* 86 */ , 
"Coming soon!" /* 87 */ , 
"Pack and Compress SARC.SZS" /* 88 */ , 
"Decompress and Extract SARC.SZS" /* 89 */ , 
"Pack SARC" /* 90 */ , 
"Extract SARC" /* 91 */ , 
"Compress SZS" /* 92 */ , 
"Decompress SZS" /* 93 */ , 
"Hide Keys" /* 94 */ , 
"Import Game Database" /* 95 */ , 
"Delete All Keys" /* 96 */ , 
"Delete Game Database" /* 97 */ , 
"Wii U Starbuck Ancast Key" /* 98 */ , 
"Import Key" /* 99 */ , 
"Wii U Espresso Ancast Key" /* 100 */ , 
"About Uwizard" /* 101 */ , 
"Wii U Common Key" /* 102 */ , 
"Check For Updates" /* 103 */ , 
"Start Download" /* 104 */ , 
"Stop Download" /* 105 */ , 
"This removes all directories from the list displayed above. The games themselves are not deleted." /* 106 */ , 
"Adds a folder to the list above. All Wii U games within that folder will be displayed in the list above." /* 107 */ , 
"Zeroes unused data. This allows the backup to be compressed more efficiently using NTFS native compression. " /* 108 */ , 
"Saves any modifications to the game information (like inputting the title key) to a permanent record." /* 109 */ , 
"Deletes all titles from the easy-access list." /* 110 */ , 
"Deletes the selected title from the easy-access list." /* 111 */ , 
"Adds the currently entered title and version to the easy-access list." /* 112 */ , 
"This list provides an easy way to choose NUS titles to download." /* 113 */ , 
"NUS title version. If this is left blank, then the latest version will be downloaded." /* 114 */ , 
"NUS title ID. This MUST be 16 characters long." /* 115 */ , 
"Compiles all files within a folder into a SARC archive, then compresses the archive with Yaz0." /* 116 */ , 
"Decompresses a Yaz0 file, and if the compressed file is a SARC archive, then it extracts all the files within the archive." /* 117 */ , 
"Compiles all files within a folder into a SARC archive." /* 118 */ , 
"Extracts all the files within a SARC archive." /* 119 */ , 
"Compresses a file with Yaz0." /* 120 */ , 
"Decompresses a Yaz0 file." /* 121 */ , 
"Hides all Nintendo-proprietary keys from non-active boxes." /* 122 */ , 
"This permanently deletes all Nintendo-Proprietary keys including title keys." /* 123 */ , 
"This permanently deletes all information about all games." /* 124 */ , 
"OK" /* 125 */ , 
"Copyright 2015 Mysteriosoft" /* 126 */ , 
"Hosted at wiiubrew.net" /* 127 */ , 
"A ticket is required to decrypt the contents, but a ticket for this title is not available on Nintendo's server. Would you like to select a ticket file to use? The ticket in a Wii U game disc for the same game from NUS is found in \"system\\02\\title.tik\"." /* 128 */ , 
"Yes" /* 129 */ , 
"No" /* 130 */ , 
"Downloading Title {0} v{1}... {2} [Latest]" /* 131 */ , 
"Storing Encrypted Content..." /* 132 */ , 
"Downloading TMD..." /* 133 */ , 
"Downloading TMD Failed: " /* 134 */ , 
"Parsing TMD..." /* 135 */ , 
"Title Version: " /* 136 */ , 
"{0} Contents" /* 137 */ , 
"{0} files, {1} bytes" /* 138 */ , 
"Downloading Ticket..." /* 139 */ , 
"Downloading Ticket Failed: " /* 140 */ , 
"Parsing Ticket..." /* 141 */ , 
"Ticket Unavailable" /* 142 */ , 
"Downloading Content #{0} of {1}... ({2} bytes) to " /* 143 */ , 
"Using Local File, Skipping..." /* 144 */ , 
"The download operation has been canceled." /* 145 */ , 
"Downloading Content #{0} of {1} failed..." /* 146 */ , 
"Credits:\r\n  Mr. Mysterio - Programmer of Uwizard\r\n  Crediar - Programmer of DiscU and CDecrypt\r\n  MasterF0x - Distributor of BFSTM Decoder\r\n  GameTDB - Game Covers\r\n  VinsCool, capito27, phanteon, send0r - Translation\r\n\r\nChangeLog:\r\n  v1.1.3\r\n    German language added. \r\n    Spanish language added.\r\n    Minor bug fixes.\r\n\r\n  v1.1.2\r\n    BFWAV decoder added.\r\n    MP3 compiler added.\r\n\r\n  v1.1.1\r\n    SZS and SARC archive management added.\r\n    BFSTM multi-select and optional channel separation added.\r\n    Command line interface added.\r\n    More NUS titles added to the easy-access list.\r\n    Minor bug fixes.\r\n    \r\n  v1.1.0\r\n    NUS Downloader U added.\r\n    BFSTM decoder added.\r\n    List selection of Wii U games added.\r\n    Minor bug fixes.\r\n    \r\n  v1.0.1\r\n    Option to hide keys added.\r\n    Minor bug fixes.\r\n\r\n  v1.0.0\r\n    Program Creation" /* 147 */ , 
"Export Game Database" /* 148 */ , 
"This game database was generated by a newer version of Uwizard. It may be incompatible." /* 149 */ , 
"Binary & Text Files|*.bin;*.txt" /* 150 */ , 
"Text Files|*.txt|All Files|*.*" /* 151 */ , 
"All Files|*.*" /* 152 */ , 
"Decode Wii U Sound Stream to WAV(s)" /* 153 */ , 
"Exception:" /* 154 */ , 
"SARC Archives|*.sarc|All Files|*.*" /* 155 */ , 
"Error extracting SARC archive!" /* 156 */ , 
"Select a folder to pack into a SARC archive." /* 157 */ , 
"Error packing SARC archive!" /* 158 */ , 
"Yaz0 Compressed Files|*.szs|All Files|*.*" /* 159 */ , 
"This file is not Yaz0 compressed!" /* 160 */ , 
"Error decompressing SZS file!" /* 161 */ , 
"Error compressing SZS file!" /* 162 */ , 
"Select a folder to pack and compress into a SARC.SZS compressed archive." /* 163 */ , 
"Export Channels Separately" /* 164 */ , 
"Exports all the channels from one Wii U Sound Stream to multiple files instead of mixing them into one." /* 165 */ , 
"Decode Wii U Sound Stream to MP3(s)" /* 166 */ , 
"Decode Wii U Sound Streams to MP3s" /* 167 */ , 
"Only each individual channel can be converted to MP3. Do you want convert each channel separetely?" /* 168 */ , 
"Wii U Sound Streams|*.bfstm;*.bfwav" /* 169 */ , 
"WAV Sound Files|*.wav|MP3 Sound Files|*.mp3" /* 170 */ , 
"Please select a language for Uwizard." /* 171 */ 
            },
#endregion
#region FRENCH_UWIZARD
           new string[] { // French
"Vérifié correct par SHA1" /* 0 */ , 
"Verifié Incorrect par SHA1" /* 1 */ , 
"Aucune Clé Entrée" /* 2 */ , 
"Aucun SHA1 Disponible" /* 3 */ , 
"Le fichier de configuration est manquant!! Les paramètres et les clés systèmes sont perdues." /* 4 */ , 
"Caractère Hex Invalide" /* 5 */ , 
"Téléchargement" /* 6 */ , 
"Lecture" /* 7 */ , 
"Fichier image de disque Wii U invalide. Peut-être avez-vous oublié de le décompresser?" /* 8 */ , 
"Recherche dans la base de données..." /* 9 */ , 
"Ce jeu n’est pas dans la base de données. S’il vous plaît entrer un nom:" /* 10 */ , 
"Entrer le Nom du Jeu" /* 11 */ , 
"PAL: Europe" /* 12 */ , 
"NTSC: Japon" /* 13 */ , 
"PAL: Australie" /* 14 */ , 
"NTSC: Amérique du Nord" /* 15 */ , 
"Recherche dans GameTDB pour des covers..." /* 16 */ , 
"Jeux Wii U|*.wud|Tous les fichiers|*.*" /* 17 */ , 
"La disc title key est requise pour décrypter les données." /* 18 */ , 
"La common key est requise pour décrypter les données." /* 19 */ , 
"La disc title key est invalide." /* 20 */ , 
"La common key est invalide." /* 21 */ , 
"Sélectionner où sauvegarder les fichiers extraits." /* 22 */ , 
"Erreur Durant l’Extraction des Fichiers!" /* 23 */ , 
"version" /* 24 */ , 
"Uwizard a bien été mis à jour à la version" /* 25 */ , 
"Uwizard a été mis à jour à la version {0}, mais dû à une erreur durant l’opération, certaine de vos données peuvent avoir été endommagées." /* 26 */ , 
"La liste de jeux est à jour." /* 27 */ , 
"{0} jeux ajoutés et {1} jeux mis à jour depuis gametdb.com" /* 28 */ , 
"{0} jeu ajouté et {1} jeux mis à jour depuis gametdb.com" /* 29 */ , 
"{0} jeux ajoutés et {1} jeu mis à jour depuis gametdb.com" /* 30 */ , 
"{0} jeu ajouté et {1} jeu mis à jour depuis gametdb.com" /* 31 */ , 
"Erreur lors du téléchargement depuis wiiubrew.net. Mise à jour annulée." /* 32 */ , 
"Version du fichier corrompue sur wiiubrew.net!" /* 33 */ , 
"ERREUR" /* 34 */ , 
"Une nouvelle version de Uwizard est disponible. Voulez-vous mettre à jour de la version {0} vers {1} ?" /* 35 */ , 
"Uwizard est à jour!" /* 36 */ , 
"Êtes-vous sûr de vouloir supprimer toutes les clés incluant les title keys?" /* 37 */ , 
"Toutes les clés ont été supprimées!" /* 38 */ , 
"Êtes-vous sûr de vouloir supprimer toutes les informations sur tous les jeux?" /* 39 */ , 
"Vous devez voyager dans le temps pour pouvoir utiliser cette fonctionnalité! :)" /* 40 */ , 
"Décryptage des données..." /* 41 */ , 
"Décryptage des données complété." /* 42 */ , 
"Erreur lors de la décryption des données!" /* 43 */ , 
"Ouverture du dossier de sortie..." /* 44 */ , 
"Début du téléchargement depuis NUS. Veuillez être patient!" /* 45 */ , 
"Téléchargement depuis NUS Terminé." /* 46 */ , 
"Téléchargement échoué:" /* 47 */ , 
"Soit le flux audio Wii U est invalide, ou bien le fichier est utilisé par un autre programme." /* 48 */ , 
"Sélectionnez où rechercher des fichiers audio." /* 49 */ , 
"Il n'y a pas de fichiers audio compatibles dans le répertoire sélectionné!" /* 50 */ , 
"Erreur lors de la conversion de" /* 51 */ , 
"Sélectionner un dossier contenant des jeux Wii U à ajouter à la liste." /* 52 */ , 
"Vous n’avez pas sauvegardé les modifications des informations du jeu Wii U. Ceci inclue le nom et la title key. Voulez-vous sauvegarder les modifications maintenant?" /* 53 */ , 
"La common key est requise pour décrypter les données." /* 54 */ , 
"Entrez le nom du titre à ajouter." /* 55 */ , 
"Gestionnaire de WUD" /* 56 */ , 
"NUS Downloader U" /* 57 */ , 
"Gestionnaire de fichier audio" /* 58 */ , 
"Gestionnaire d'archives" /* 59 */ , 
"Paramètres" /* 60 */ , 
"Afficher la Liste de Jeux" /* 61 */ , 
"Vider la Liste de Dossiers" /* 62 */ , 
"Ajouter un Dossier" /* 63 */ , 
"Scrubber un Jeu Wii U" /* 64 */ , 
"Afficher le Cover Complet" /* 65 */ , 
"Sauvegarder les Informations du Jeu" /* 66 */ , 
"Extraire les Fichiers du Jeu" /* 67 */ , 
"Infos du Jeu" /* 68 */ , 
"Title Key" /* 69 */ , 
"Importer" /* 70 */ , 
"Nom du Jeu" /* 71 */ , 
"ID du Jeu" /* 72 */ , 
"Ouvrir un jeu Wii U" /* 73 */ , 
"Vider la Liste" /* 74 */ , 
"Supprimer un Titre" /* 75 */ , 
"Ajouter un Titre" /* 76 */ , 
"Version:" /* 77 */ , 
"ID du Titre:" /* 78 */ , 
"Décrypter les Données" /* 79 */ , 
"Ouvrir un Dossier" /* 80 */ , 
"Jouer un Fichier Audio" /* 81 */ , 
"Sélectionner un Dossier" /* 82 */ , 
"Fichiers Audio Dans le Dossier Sélectionné" /* 83 */ , 
"Décoder un Flux Audio Wii U" /* 84 */ , 
"Convertir des Flux Audio Wii U en WAVs" /* 85 */ , 
"Convertir un Flux Audio Wii U au format WAV" /* 86 */ , 
"Bientôt disponible!" /* 87 */ , 
"Empaqueter et Compresser SARC.SZS" /* 88 */ , 
"Décompresser et Extraire SARC.SZS" /* 89 */ , 
"Empaqueter SARC" /* 90 */ , 
"Extraire SARC" /* 91 */ , 
"Compression SZS" /* 92 */ , 
"Décompression SZS" /* 93 */ , 
"Cacher les Clés" /* 94 */ , 
"Importer la Base de Donnée des Jeux" /* 95 */ , 
"Supprimer Toutes les Clés" /* 96 */ , 
"Supprimer la Base de Données des Jeux" /* 97 */ , 
"Wii U Starbuck Ancast Key" /* 98 */ , 
"Importer" /* 99 */ , 
"Wii U Espresso Ancast Key" /* 100 */ , 
"À propos de Uwizard" /* 101 */ , 
"Wii U Common Key" /* 102 */ , 
"Vérifier des Mises à Jour" /* 103 */ , 
"Démarrer le Téléchargement" /* 104 */ , 
"Arrêter le Téléchargement" /* 105 */ , 
"Ceci enlève tous les dossiers de la liste ci-dessus. Les jeux ne seront pas supprimés." /* 106 */ , 
"Ajoute un dossier dans la liste ci-dessus. Tous les jeux Wii U contenus dans ce dossier seront affichés dans cette liste." /* 107 */ , 
"Suppression des données non utilisées. Ceci permet au backup d’être compressé plus efficacement utilisant la compression NTFS native." /* 108 */ , 
"Sauvegarde de toute les informations du jeu modifiées (comme la title key) de façon permanente." /* 109 */ , 
"Supprime tous les titres de la liste." /* 110 */ , 
"Supprime les titres sélectionnés de la liste." /* 111 */ , 
"Ajoute le titre présentement entré et la version dans la liste." /* 112 */ , 
"Cette liste permet de choisir aisément les titres NUS à télécharger." /* 113 */ , 
"Version du titre NUS. Si l’espace est laissé vide, la dernière version sera téléchargée." /* 114 */ , 
"ID du titre NUS. Cela DOIT faire 16 caractères." /* 115 */ , 
"Compile tous les fichier du même dossier dans une archive SARC, ensuite compresse l’archive avec Yaz0." /* 116 */ , 
"Décompresse un fichier Yaz0, et si le fichier compressé est une archive SARC, tous le fichiers contenues dans cette archive seront extraits." /* 117 */ , 
"Compile tous les fichiers dans une archive SARC." /* 118 */ , 
"Extrait tous les fichiers contenus dans une archive SARC." /* 119 */ , 
"Compresse un fichier avec Yaz0." /* 120 */ , 
"Decompresse un fichier Yaz0." /* 121 */ , 
"Cache toutes les clés appartenant à Nintendo d’un boîte inactive." /* 122 */ , 
"Supprime de façon permanente toutes les clés appartenant à Nintendo, incluant les title keys." /* 123 */ , 
"Supprime de façon permanente toutes les informations sur tous les jeux." /* 124 */ , 
"OK" /* 125 */ , 
"Copyright 2015 Mysteriosoft" /* 126 */ , 
"Disponible sur wiiubrew.net" /* 127 */ , 
"Un ticket est requis pour décrypter le contenu, mais ce ticket n'est pas disponible sur les serveurs de Nintendo. Voulez-vous sélectionner un ticket à utiliser? Le ticket d'un jeu Wii U sur disque pour le même jeu téléchargeable via NUS se trouve dans \"system\\02\\title.tik\"." /* 128 */ , 
"Oui" /* 129 */ , 
"Non" /* 130 */ , 
"Téléchargement du Titre {0} v{1}... {2} [Plus Récent]" /* 131 */ , 
"Classement des Fichiers Encryptés..." /* 132 */ , 
"Téléchargement du TMD..." /* 133 */ , 
"Téléchargement du TMD Échoué:" /* 134 */ , 
"Analyse du TMD..." /* 135 */ , 
"Version du Titre:" /* 136 */ , 
"{0} Contenus" /* 137 */ , 
"{0} fichiers, {1} octets" /* 138 */ , 
"Téléchargement du Ticket..." /* 139 */ , 
"Téléchargement du Ticket Échoué:" /* 140 */ , 
"Analyse du Ticket..." /* 141 */ , 
"Ticket Indisponible" /* 142 */ , 
"Téléchargement du Contenu #{0} de {1}... ({2} octets) de" /* 143 */ , 
"Utilisation d'un Fichier Local, Passe..." /* 144 */ , 
"Le téléchargement a été annulé." /* 145 */ , 
"Téléchargement du Contenu #{0} de {1} échoué..." /* 146 */ , 
"Crédits:\r\n  Mr. Mysterio - Programmeur de Uwizard\r\n  Crediar - Programmeur de DiscU et CDecrypt\r\n  MasterF0x - Distributeurr de BFSTM Decoder\r\n  GameTDB - Game Covers\r\n  VinsCool, capito27, phanteon, send0r - Traduction\r\n\r\nChangeLog:\r\n  v1.1.3\r\n    Langue Allemande ajouté.\r\n    Langue Espagnole ajouté.\r\n    Correction de bugs mineurs.\r\n\r\n  v1.1.2\r\n    Décodeur BFWAV ajouté.\r\n    Compilateur MP3 ajouté.\r\n\r\n  v1.1.1\r\n    Système d'archives SZS et SARC ajouté.\r\n    Multi-sélection et choix de séparation de flux ajouté au gestionnaire de fichiers BFSTM.\r\n    Interface en lignes de commande ajoutée.\r\n    Plus de titres NUS ajoutés à la liste d'accès rapide.\r\n    Correction de bugs mineurs.\r\n\r\n  v1.1.0\r\n    NUS Downloader U ajouté.\r\n    BFSTM decoder ajouté.\r\n    Liste de sélection de jeux Wii U ajouté.\r\n    Correction de bugs mineurs.\r\n\r\n  v1.0.1\r\n    Option pour cacher les clés.\r\n    Correction de bugs mineurs.\r\n\r\n  v1.0.0\r\n    Version initiale" /* 147 */ , 
"Exportation de la base de données des jeux" /* 148 */ , 
"Cette base de données de jeux a été générée par une version plus récente de Uwizard. Elle pourrait être incompatible." /* 149 */ , 
"Fichiers Binaires et Fichiers Texte|*.bin;*.txt|Tous les Fichiers|*.*" /* 150 */ , 
"Fichiers Texte|*.txt|Tous les Fichiers|*.*" /* 151 */ , 
"Tous les Fichiers|*.*" /* 152 */ , 
"Convertir un Flux Audio Wii U au format WAV(s)" /* 153 */ , 
"Exception:" /* 154 */ , 
"Archives SARC|*.sarc|Tous les Fichiers|*.*" /* 155 */ , 
"Une erreur s'est produite durant l'extraction de l'archive SARC!" /* 156 */ , 
"Sélectionnez un dossier a empaqueter en une archive SARC." /* 157 */ , 
"Une erreur s'est produite durant l'empaquetage de l'archive SARC!" /* 158 */ , 
"Fichiers Yaz0 compressés|*.szs|Tous les fichiers|*.*" /* 159 */ , 
"Ce fichier n'a pas été compressé avec Yaz0!" /* 160 */ , 
"Une erreur s'est produite durant la décompression du fichier SZS!" /* 161 */ , 
"Une erreur s'est produite durant la compression du fichier SZS!" /* 162 */ , 
"Sélectionnez un dossier à empaqueter et compresser en une archive SARC.SZS." /* 163 */ , 
"Exporter les flux séparement" /* 164 */ , 
"Exporter tous les canaux d'un flux audio Wii U en plusieurs fichiers au lieu de les mélanger en un seul." /* 165 */ , 
"Convertir un Flux Audio Wii U au format MP3(s)" /* 166 */ , 
"Convertir des Flux Audio Wii U en MP3s" /* 167 */ , 
"Un seul canal peut être converti en MP3. Voulez-vous convertir chaque canal séparement?" /* 168 */ , 
"Flux Audio Wii U|*.bfstm;*.bfwav" /* 169 */ , 
"Fichiers Audio WAV|*.wav|Fichiers Audio MP3|*.mp3" /* 170 */ , 
"Veuillez sélectionner la langue pour Uwizard." /* 171 */ 
            },
#endregion
#region PORTUGUESE_UWIZARD
            new string[] { // Portugese
"Verificado correto por SHA1" /* 0 */ , 
"Verificado incorreto por SHA1" /* 1 */ , 
"Nenhuma chave enterada" /* 2 */ , 
"SHA1 não disponivel" /* 3 */ , 
"O ficheiro de configuração não foi encontrado! Os seus parámetros e chaves systema forão perdidos." /* 4 */ , 
"Caractere hex invalido" /* 5 */ , 
"Descargando " /* 6 */ , 
"Lendo " /* 7 */ , 
"Wii U disc Image Invalida. Se calhar esqueceu-se de desarquivar o ficheiro?" /* 8 */ , 
"Procurando o banco de dados..." /* 9 */ , 
"Este jogo não esta no banco de dados. Por favor, entre o nome dele:" /* 10 */ , 
"Entre o nome do jogo" /* 11 */ , 
"PAL: Europa" /* 12 */ , 
"NTSC: Japão" /* 13 */ , 
"PAL: Australia" /* 14 */ , 
"NTSC: América do Norte" /* 15 */ , 
"Procurando coberturas sobre GameTDB..." /* 16 */ , 
"Jogo Wii U|*.wud|Todos os fichieiros|*.*" /* 17 */ , 
"A title key é necessária para decriptar os dados." /* 18 */ , 
"A common key é necessária para decriptar os dados." /* 19 */ , 
"A title key não é valida." /* 20 */ , 
"A common key não é valida." /* 21 */ , 
"Seleccionar onde guardar os ficheiros estraídos." /* 22 */ , 
"um erro aconteceu durante a extração dos ficheiros!" /* 23 */ , 
"versão " /* 24 */ , 
"Uwizard foi corretamente atualizado para a versão " /* 25 */ , 
"Uwizard foi atualizado para a versão {0}, mas por caso de un erro durante a atualização, alguns dados foram talvez perdidos." /* 26 */ , 
"A lista de Jogos esta atualizada." /* 27 */ , 
"{0} jogos adicionados e {1} jogos atualizados por gametdb.com" /* 28 */ , 
"{0} jogo adicionado e {1} jogos atualizados por gametdb.com" /* 29 */ , 
"{0} jogos adicionados e {1} jogo atualizado por gametdb.com" /* 30 */ , 
"{0} jogo adicionado e {1} jogo atualizado por gametdb.com" /* 31 */ , 
"Um erro aconteceu durante o descargamento das informações de versão por gametdb.com . A atualização foi cancelada." /* 32 */ , 
"Informações de versão incorretas sobre wiiubrew.net!" /* 33 */ , 
"ERRO" /* 34 */ , 
"Uma nova versão de Uwizard esta disponivel. Quer atualizar de {0} para {1} ?" /* 35 */ , 
"Uwizard esta atualizado!" /* 36 */ , 
"Tem a certeza de querer apagar definitivamente todas as chaves, incluindo as title keys?" /* 37 */ , 
"Todas as chaves foram apagadas corretamente!" /* 38 */ , 
"Tem a certeza de querer apagar definitivamente todas as informações de jogos?" /* 39 */ , 
"Tem de viajar para o futuro para usar essa função :)" /* 40 */ , 
"Decriptagem dos dados..." /* 41 */ , 
"Decriptagem dos dados concluida." /* 42 */ , 
"Um erro aconteceu durante a decriptagem dos dados!" /* 43 */ , 
"Abrindo a pasta de saída..." /* 44 */ , 
"Iniciando descargamento NUS. Por favor seja paciente!" /* 45 */ , 
"Descargamento NUS Concluido." /* 46 */ , 
"O descargamento falhou: " /* 47 */ , 
"Ou este não é um válido Wii U Sound Stream, ou o arquivo está em uso por outro programa." /* 48 */ , 
"Selecione onde procurar por arquivos de som." /* 49 */ , 
"Não há arquivos de som compatíveis no diretório selecionado!" /* 50 */ , 
"Um erro aconteceu durante a converção de " /* 51 */ , 
"Seleccione uma pasta com jogos Wii U para adicionar nesta lista." /* 52 */ , 
"Ainda não guardou as modifications sobre as informações do jogo Wii U. Isto inclui o nome e a title key. Quer guardar as modifications?" /* 53 */ , 
"A common key è necessária para decriptar." /* 54 */ , 
"Entre o nome do titelo a adicionar." /* 55 */ , 
"WUD Manager" /* 56 */ , 
"NUS Downloader U" /* 57 */ , 
"Sound Manager" /* 58 */ , 
"Archive Manager" /* 59 */ , 
"Configuração " /* 60 */ , 
"Mostrar a lista de jogos" /* 61 */ , 
"Apagar a lista de pastas" /* 62 */ , 
"Adicionar uma pasta" /* 63 */ , 
"Scrub o jogo Wii U" /* 64 */ , 
"Mostrar a cobertura completa" /* 65 */ , 
"Guardar as informações do jogo" /* 66 */ , 
"Extrair os ficheiros do jogo" /* 67 */ , 
"Informações do jogo" /* 68 */ , 
"Title Key" /* 69 */ , 
"Importar" /* 70 */ , 
"Nome do jogo" /* 71 */ , 
"ID do jogo" /* 72 */ , 
"Abrir jogo Wii U" /* 73 */ , 
"Apagar a lista List" /* 74 */ , 
"Apagar Title" /* 75 */ , 
"Adicionar Title" /* 76 */ , 
"Versão:" /* 77 */ , 
"Title ID:" /* 78 */ , 
"Decriptar dados" /* 79 */ , 
"Abrir pasta" /* 80 */ , 
"jogar fluxo de som" /* 81 */ , 
"Seleccionar pasta" /* 82 */ , 
"Ficheiros som na pasta seleccionada" /* 83 */ , 
"Decodificar um fluxo de Wii U Sound" /* 84 */ , 
"Converso Wii U Streams som para WAVs" /* 85 */ , 
"Converso Wii U Sound Stream para WAV" /* 86 */ , 
"Coming soon!" /* 87 */ , 
"Empacotar and Compressar SARC.SZS" /* 88 */ , 
"Decompressar and Extrair SARC.SZS" /* 89 */ , 
"Empacotar SARC" /* 90 */ , 
"Extrair SARC" /* 91 */ , 
"Compressar SZS" /* 92 */ , 
"Decompressar SZS" /* 93 */ , 
"Esconder chaves" /* 94 */ , 
"Import Game Database" /* 95 */ , 
"Apagar TODAS as chaves" /* 96 */ , 
"Apagar o banco de dados de jogos" /* 97 */ , 
"Wii U Starbuck Ancast Key" /* 98 */ , 
"Importar" /* 99 */ , 
"Wii U Espresso Ancast Key" /* 100 */ , 
"Sobre Uwizard" /* 101 */ , 
"Wii U Common Key" /* 102 */ , 
"Procurar atualizações" /* 103 */ , 
"Iniciar decarrgamento" /* 104 */ , 
"Parar decarrgamento" /* 105 */ , 
"Isto apaga todas as pastas da lista acima. Os jogos não serão apagados." /* 106 */ , 
"Adiciona uma pasta na lista acima. Todos os jogos Wii U na pasta seleccionada serão incluidos na lista." /* 107 */ , 
"Apaga dados inúteis. Permitindo au ficheiro de ser compressado mais effeicientement usando compressões NTFS nativas. " /* 108 */ , 
"Guarda todas as modificações das informações do jogo (como entrar a title key) para un registro permanente." /* 109 */ , 
"Apaga todos os titelos da lista." /* 110 */ , 
"Apaga o titelo seleccionado da lista." /* 111 */ , 
"Adiciona o titelo e a versão atúais na lista." /* 112 */ , 
"Esta lista fornece uma simples maneira para selecionar os titelos a descargar do NUS." /* 113 */ , 
"NUS title versão. se esta vazio, a ultima versão sera descargada." /* 114 */ , 
"NUS title ID. DEVE ser exatamente 16 caracteres." /* 115 */ , 
"Compila todos os ficheiros numa pasta em um arquivo SARC, depois compressa o arquivo com Yaz0." /* 116 */ , 
"Decompressa um ficheiro Yaz0, e se o ficheiro compressado e um arquivo SARC, extrai todos os ficheiro do arquivo." /* 117 */ , 
"Compila todos os ficheiros numa pasta em un arquivo SARC." /* 118 */ , 
"Extrai todos os ficheiros de um arquivo SARC ." /* 119 */ , 
"Compressa um ficheiro com Yaz0." /* 120 */ , 
"Decompressa um ficheiro Yaz0." /* 121 */ , 
"Esconde todas as chaves de Nintendo." /* 122 */ , 
"Isto apaga definitivamente todas as chaves de Nintendo, incluindo as title keys." /* 123 */ , 
"Isto apaga definitivamente todas as informações sobre todos os jogos." /* 124 */ , 
"OK" /* 125 */ , 
"Copyright 2015 Mysteriosoft" /* 126 */ , 
"Hospedado sobre wiiubrew.net" /* 127 */ , 
"Um ticket e necessário para decriptar os dados, mas o ticket para este title não esta disponivel nos servidores de Nintendo. deseja seleccionar um ficheiro ticket manualmente? O ticket no disco de um jogo Wii U para o mesmo jogo desde NUS pode ser encontrado em \"system\\02\\title.tik\" sobre o disco." /* 128 */ , 
"Sim" /* 129 */ , 
"Não" /* 130 */ , 
"Descargando Title {0} v{1}... {2} [O mais recente]" /* 131 */ , 
"Guardando dados criptados..." /* 132 */ , 
"Descargando TMD..." /* 133 */ , 
"Descargamento do TMD falhou: " /* 134 */ , 
"Análise do TMD..." /* 135 */ , 
"Title Version: " /* 136 */ , 
"{0} dados" /* 137 */ , 
"{0} ficheiros, {1} bytes" /* 138 */ , 
"Descargando Ticket..." /* 139 */ , 
"Descargamento do Ticket falhou: " /* 140 */ , 
"Análise Ticket..." /* 141 */ , 
"Ticket não disponivel" /* 142 */ , 
"Descargando dado #{0} sobre {1}... ({2} bytes) para " /* 143 */ , 
"usando ficheiro local, passando..." /* 144 */ , 
"O descargamento foi cancelado." /* 145 */ , 
"Descargamento do dado #{0} sobre {1} falhou..." /* 146 */ , 
"Creditos:\r\n  Mr. Mysterio - Programador de Uwizard\r\n  Crediar - Programador de DiscU e CDecrypt\r\n  MasterF0x - Distribuidor de BFSTM Decoder \r\n  GameTDB - Coberturas de jogos\r\n  VinsCool, capito27, phanteon, send0r - tradução\r\n\r\nChangeLog:\r\n  v1.1.3\r\n    Língua Alemã acrescentou.\r\n    Língua Espanhola acrescentou.\r\n    Correção de erros minors.\r\n\r\n  v1.1.2\r\n    Descodificador BFWAV adicionado.\r\n    Compilador MP3 adicionado.\r\n\r\n  v1.1.1\r\n    Systema d'arquivos SZS e SARC adicionado.\r\n    Multi-seleção e escolha de sepalação de fluxo audio addicionado au gestor de ficheiros BFSTM.\r\n    Interface em ligna de comandos addicionada.\r\n    Mais titelos NUS addicionados na lista de acceso rapido.\r\n    Correção de erros minors.\r\n\r\n  v1.1.0\r\n    NUS Downloader U addicionado.\r\n    BFSTM decoder addicionado.\r\n    Lista de seleccão de jogos Wii U addicionada.\r\n    Correção de erros minors.\r\n\r\n  v1.0.1\r\n    Opção para esconder as chaves addicionada.\r\n    Correção de erros minors.\r\n\r\n  v1.0.0\r\n    Criação do programa" /* 147 */ , 
"Exportação de banco de dados dos jogos" /* 148 */ , 
"Este banco de dados foi generado por uma verção mais recente de Uwizard. Pode ser incompativel." /* 149 */ , 
"Ficheiros Binarios & Ficheiros Texto|*.bin;*.txt|Todos os ficheiros|*.*" /* 150 */ , 
"Ficheiros Texto|*.txt|Todos os ficheiros|*.*" /* 151 */ , 
"Todos os ficheiros|*.*" /* 152 */ , 
"Converso Wii U Sound Stream para WAV(s)" /* 153 */ , 
"Exceção:" /* 154 */ , 
"Arcivos SARC|*.sarc|Todos os ficheiros|*.*" /* 155 */ , 
"Um erro aconteceu durante a extração do arquivo SARC!" /* 156 */ , 
"Selecione uma pasta a empacotar num arquivo SARC." /* 157 */ , 
"Um erro aconteceu durante o empacotamento do arquivo SARC!" /* 158 */ , 
"Ficheiros Yaz0 compressados|*.szs|Todos os ficheiros|*.*" /* 159 */ , 
"Este ficheiro não foi compressado por Yaz0!" /* 160 */ , 
"Um erro aconteceu durante a decompreção do ficheiro SZS!" /* 161 */ , 
"Um erro aconteceu durante a compreção do ficheiro SZS!" /* 162 */ , 
"Selecione uma pasta para empacotar e compressar em un arquivo SARC.SZS compressado." /* 163 */ , 
"Exportar os fluxos separadamente" /* 164 */ , 
"As exportações de todos os canais de um Wii U Sound Stream para múltiplos arquivos em vez de misturá-los em um só." /* 165 */ , 
"Converso Wii U Sound Stream para MP3(s)" /* 166 */ , 
"Converso Wii U Streams som para MP3" /* 167 */ , 
"Apenas cada canal individual pode ser convertido para MP3. Você quer converter cada canal separetely?" /* 168 */ , 
"Wii U Streams Som|*.bfstm;*.bfwav" /* 169 */ , 
"WAV Arquivos de Som|*.wav|Arquivos de Som MP3|*.mp3" /* 170 */ , 
"Escolha o idioma de Uwizard." /* 171 */ 
           },
#endregion
#region GERMAN_UWIZARD
            new string[] {
"Stimmt mit SHA1-Hash überein" /* 0 */ , 
"Stimmt nicht mit SHA1-Hash überein" /* 1 */ , 
"Kein Schlüssel eingetragen" /* 2 */ , 
"SHA1 ist nicht verfügbar" /* 3 */ , 
"Die Einstellungs-Datei fehlt! Deine Einstellungen und System-Schlüssel sind verloren." /* 4 */ , 
"Ungültiger Hex String" /* 5 */ , 
"Lade herunter" /* 6 */ , 
"Lese" /* 7 */ , 
"Ungültiges Wii U Disk-Image. Hast du vergessen die Datei zu entzippen?" /* 8 */ , 
"Durchsuche Spiele-Datenbank..." /* 9 */ , 
"Dieses Spiel ist nicht in der Datenbank. Bitte trage den Namen ein:" /* 10 */ , 
"Spiel-Name eintragen" /* 11 */ , 
"PAL: Europa" /* 12 */ , 
"NTSC: Japan" /* 13 */ , 
"PAL: Australien" /* 14 */ , 
"NTSC: Nord-Amerika" /* 15 */ , 
"Durchsuche GameTDB nach Cover..." /* 16 */ , 
"Wii U Spiele|*.wud|Alle Dateien|*.*" /* 17 */ , 
"Der Disk Title Key wird benötigt, um die Daten zu entschlüsseln." /* 18 */ , 
"Der Common Key wird benötigt, um die Daten zu entschlüsseln." /* 19 */ , 
"Der Disk Title Key ist ungültig." /* 20 */ , 
"Der Common Key ist ungültig." /* 21 */ , 
"Wähle den Ausgabeordner für die extrahierten Daten aus." /* 22 */ , 
"Fehler beim Extrahieren der Daten!" /* 23 */ , 
"Version " /* 24 */ , 
"Uwizard wurde erfolgreich aktualisiert auf Version" /* 25 */ , 
"Uwizard wurde auf Version {0} aktualisiert. Aufgrund eines Fehlers während des Aktualisierungsprozesses können einige deiner Daten beschädigt worden sein." /* 26 */ , 
"Die Spiele-Liste ist aktuell." /* 27 */ , 
"{0} Spiele hinzugefügt und {1} Spiele über gametdb.com aktualisiert" /* 28 */ , 
"{0} Spiel hinzugefügt und {1} Spiele über gametdb.com aktualisiert" /* 29 */ , 
"{0} Spiele hinzugefügt und {1} Spiel über gametdb.com aktualisiert" /* 30 */ , 
"{0} Spiel hinzugefügt und {1} Spiel über gametdb.com aktualisiert" /* 31 */ , 
"Fehler beim beziehen der Versions-Informationen über wiiubrew.net. Aktualisierungsprozess abgebrochen." /* 32 */ , 
"Fehlerhafte Versions-Datei auf wiiubrew.net!" /* 33 */ , 
"FEHLER" /* 34 */ , 
"Eine neue Version von Uwizard ist verfügbar. Möchtest du von Version {0} auf {1} aktualisieren?" /* 35 */ , 
"Uwizard ist auf dem neuesten Stand!" /* 36 */ , 
"Bist du dir sicher, dass du alle Schlüssel inklusive der Title Keys dauerhaft löschen möchtest?" /* 37 */ , 
"Alle Schlüssel wurden erfolgreich gelöscht!" /* 38 */ , 
"Bist du dir sicher, dass du alle Spiele-Informationen dauerhaft löschen möchtest?" /* 39 */ , 
"Du musst in die Zukunft reisen, um dieses Feature benutzen zu können! :)" /* 40 */ , 
"Entschlüssele Inhalte..." /* 41 */ , 
"Entschlüsseln der Inhalte abgeschlossen." /* 42 */ , 
"Fehler beim Entschlüsseln der Inhalte!" /* 43 */ , 
"Öffne Ausgabe-Dateipfad..." /* 44 */ , 
"Starte NUS Download. Bitte warten!" /* 45 */ , 
"NUS Download abgeschlossen." /* 46 */ , 
"Download fehlgeschlagen:" /* 47 */ , 
"Entweder ist dies kein gültiger Wii U Sound Stream oder die Datei wird im Moment von einem anderen Programm verwendet." /* 48 */ , 
"Wähle einen Ordner, in dem nach Audio-Dateien gesucht werden soll." /* 49 */ , 
"Im ausgewählten Ordner sind keine kompatiblen Audio-Dateien vorhanden!" /* 50 */ , 
"Fehler beim Konvertieren" /* 51 */ , 
"Wähle einen Ordner mit Wii U Spielen, um diese zu der Liste hinzuzufügen." /* 52 */ , 
"Du hast deine Änderungen an den Informationen des aktuellen Wii U Spiels nicht gespeichert. Dies beinhaltet den Namen und den Title Key. Möchtest du die Änderungen jetzt Speichern?" /* 53 */ , 
"Der Common Key wird benötigt, um die Daten zu entschlüsseln." /* 54 */ , 
"Trage den Namen des Titels ein, welcher hinzugefügt werden soll." /* 55 */ , 
"WUD-Manager" /* 56 */ , 
"NUS Downloader U" /* 57 */ , 
"Sound-Manager" /* 58 */ , 
"Archiv-Manager" /* 59 */ , 
"Einstellungen" /* 60 */ , 
"Spiele-Liste anzeigen" /* 61 */ , 
"Ordner-Liste löschen" /* 62 */ , 
"Ordner hinzufügen" /* 63 */ , 
"Wii U Spiel bereinigen" /* 64 */ , 
"Vollständiges Cover anzeigen" /* 65 */ , 
"Spiel-Informationen speichern" /* 66 */ , 
"Spiel-Dateien extrahieren" /* 67 */ , 
"Spiel Info" /* 68 */ , 
"Title Key" /* 69 */ , 
"Import" /* 70 */ , 
"Spiel-Name" /* 71 */ , 
"Spiel ID" /* 72 */ , 
"Wii U Spiel öffnen" /* 73 */ , 
"Liste löschen" /* 74 */ , 
"Titel löschen" /* 75 */ , 
"Titel hinzufügen" /* 76 */ , 
"Version:" /* 77 */ , 
"Title ID:" /* 78 */ , 
"Inhalte entschlüsseln" /* 79 */ , 
"Ordner öffnen" /* 80 */ , 
"Sound Stream abspielen" /* 81 */ , 
"Ordner auswählen" /* 82 */ , 
"Audio-Dateien im ausgewählten Ordner" /* 83 */ , 
"Dekodiere einen Wii U Sound Stream" /* 84 */ , 
"Dekodiere Wii U Sound Streams zu WAVs" /* 85 */ , 
"Dekodiere Wii U Sound Stream zu WAV" /* 86 */ , 
"Bald verfügbar!" /* 87 */ , 
"SARC.SZS packen und komprimieren" /* 88 */ , 
"SARC.SZS dekomprimieren und entpacken" /* 89 */ , 
"SARC packen" /* 90 */ , 
"SARC extrahieren" /* 91 */ , 
"SZS komprimieren" /* 92 */ , 
"SZS dekomprimieren" /* 93 */ , 
"Schlüssel verstecken" /* 94 */ , 
"Spiele-Datenbank importieren" /* 95 */ , 
"Alle Schlüssel löschen" /* 96 */ , 
"Spiele-Datenbank löschen" /* 97 */ , 
"Wii U Starbuck Ancast Key" /* 98 */ , 
"Schlüssel importieren" /* 99 */ , 
"Wii U Espresso Ancast Key" /* 100 */ , 
"Über Uwizard" /* 101 */ , 
"Wii U Common Key" /* 102 */ , 
"Nach Updates suchen" /* 103 */ , 
"Download starten" /* 104 */ , 
"Download abbrechen" /* 105 */ , 
"Löscht alle Verzeichnisse aus der oben angezeigten Liste. Die Spiele selbst werden nicht gelöscht." /* 106 */ , 
"Fügt der obigen Liste einen Ordner hinzu. Alle Wii U Spiele in diesem Ordner werden in dieser Liste angezeigt." /* 107 */ , 
"Überschreibt ungenutzte Daten mit Nullen. Dies erlaubt es das Backup effizienter mit der nativen NTFS-Komprimierung zu komprimieren." /* 108 */ , 
"Speichert alle Modifikationen dauerhaft in die Spiel-Informationen (wie das Eingeben des Title Keys)." /* 109 */ , 
"Löscht alle Titel von der Easy-Access-Liste." /* 110 */ , 
"Löscht den ausgewählten Titel von der Easy-Access-Liste." /* 111 */ , 
"Fügt den gerade eingegebenen Titel, sowie die Version der Easy-Access-Liste hinzu." /* 112 */ , 
"Diese Liste ist ein einfacher Weg NUS-Titel zum herunterladen auszuwählen." /* 113 */ , 
"NUS Titel-Version. Wenn dies leer gelassen wird, wird die aktuellste Version heruntergeladen." /* 114 */ , 
"NUS Title ID. MUSS 16 Zeichen lang sein." /* 115 */ , 
"Kompiliert alle Dateien in einem Ordner zu einem SARC-Archiv, um dieses dann mit Yaz0 zu komprimieren." /* 116 */ , 
"Dekomprimiert eine Yaz0-Datei. Wenn die komprimierte Datei ein SARC-Archiv ist, werden alle sich darin befindenden Dateien extrahiert." /* 117 */ , 
"Kompiliert alle Dateien in einem Ordner in ein SARC-Archiv." /* 118 */ , 
"Extrahiert alle Dateien aus einem SARC-Archiv." /* 119 */ , 
"Komprimiert eine Datei mit Yaz0." /* 120 */ , 
"Dekomprimiert eine Yaz0-Datei." /* 121 */ , 
"Versteckt alle von Nintendo geschützten Schlüssel von inaktiven Boxen." /* 122 */ , 
"Löscht dauerhaft alle von Nintendo geschützten Schlüssel inklusive der Title Keys." /* 123 */ , 
"Löscht dauerhaft alle Informationen über alle Spiele." /* 124 */ , 
"OK" /* 125 */ , 
"Copyright 2015 Mysteriosoft" /* 126 */ , 
"Gehosted auf wiiubrew.net" /* 127 */ , 
"Ein Ticket wird benötigt, um die Inhalte zu entschlüsseln. Allerdings ist kein Ticket auf Nintendos Server verfügbar. Möchtest du eine Ticket-Datei zum benutzen auswählen? Das Ticket für das gleiche Spiel vom NUS liegt auf einer Wii U Spiele-Disk in \"system\\02\\title.tik\"." /* 128 */ , 
"Ja" /* 129 */ , 
"Nein" /* 130 */ , 
"Lade Title {0} v{1}... {2} [Latest] herunter" /* 131 */ , 
"Speichere verschlüsselten Inhalt..." /* 132 */ , 
"Lade TMD herunter..." /* 133 */ , 
"Herunterladen des TMD ist fehlgeschlagen:" /* 134 */ , 
"Analysiere TMD..." /* 135 */ , 
"Title Version:" /* 136 */ , 
"{0} Inhalte" /* 137 */ , 
"{0} Dateien, {1} Bytes" /* 138 */ , 
"Lade Ticket herunter..." /* 139 */ , 
"Herunterladen des Tickets ist fehlgeschlagen:" /* 140 */ , 
"Analysiere Ticket..." /* 141 */ , 
"Ticket nicht verfügbar" /* 142 */ , 
"Lade Inhalt #{0} von {1} herunter... ({2} Bytes) von" /* 143 */ , 
"Benutze lokale Datei, überspringe..." /* 144 */ , 
"Der Download wurde abgebrochen." /* 145 */ , 
"Herunterladen des Inhalts #{0} von {1} fehlgeschlagen..." /* 146 */ , 
"Danksagungen:\r\n  Mr. Mysterio - Programmierer von Uwizard\r\n  Crediar - Programmierer von DiscU und CDecrypt\r\n  MasterF0x - Verteiler des BFSTM-Dekoders\r\n  GameTDB - Spiele-Cover\r\n  VinsCool, capito27, phanteon, send0r - Übersetzung\r\n\r\nChangeLog:\r\n  v1.1.3\r\n    Deutsch wurde als Sprache hinzugefügt.\r\n    Spanisch wurde als Sprache hinzugefügt.\r\n    Kleine Bugfixes.\r\n\r\n  v1.1.2\r\n    BFWAV-Dekodierer hinzugefügt.\r\n    MP3-Compiler hinzugefügt.\r\n\r\n  v1.1.1\r\n    SZS- und SARC-Archiv-Management hinzugefügt.\r\n    BFSTM Multi-Auswahl und optionale Kanal-Trennung hinzugefügt.\r\n    Kommandozeilen-Interface hinzugefügt.\r\n    Weitere NUS Titel zur Easy-Access-List hinzugefügt.\r\n    Kleine Bugfixes.\r\n \r\n  v1.1.0\r\n    NUS Downloader U hinzugefügt.\r\n    BFSTM-Dekodierer hinzugefügt.\r\n    Listen-Auswahl von Wii U Spielen hinzugefügt.\r\n    Kleine Bugfixes.\r\n\r\n  v1.0.1\r\n    Option zum Verstecken von Schlüsseln hinzugefügt.\r\n    Kleine Bugfixes.\r\n\r\n  v1.0.0\r\n    Programm Veröffentlichung" /* 147 */ , 
"Exportiere Spiele-Datenbank" /* 148 */ , 
"Diese Spiele-Datenbank wurde von einer neueren Version von Uwizard erstellt. Sie ist möglicherweise inkompatibel." /* 149 */ , 
"Binär- & Text-Dateien|*.bin;*.txt" /* 150 */ , 
"Text-Dateien|*.txt|Alle Dateien|*.*" /* 151 */ , 
"Alle Dateien|*.*" /* 152 */ , 
"Dekodiere Wii U Sound Stream zu WAV(s)" /* 153 */ , 
"Ausnahme:" /* 154 */ , 
"SARC-Archiv|*.sarc|Alle Dateien|*.*" /* 155 */ , 
"Fehler beim Extrahieren des SARC-Archivs!" /* 156 */ , 
"Wähle einen Ordner zum Packen und Komprimieren in ein SARC.SZS-Archiv aus." /* 157 */ , 
"Fehler beim Packen des SARC-Archivs!" /* 158 */ , 
"Yaz0-komprimierte Dateien|*.szs|Alle Dateien|*.*" /* 159 */ , 
"Diese Datei ist nicht Yaz0-komprimiert!" /* 160 */ , 
"Fehler beim Dekomprimieren der SZS-Datei!" /* 161 */ , 
"Fehler beim Komprimieren der SZS-Datei!" /* 162 */ , 
"Wähle einen Ordner zum Packen und Komprimieren in ein SARC.SZS-komprimiertes Archiv aus." /* 163 */ , 
"Exportiere Kanäle getrennt" /* 164 */ , 
"Exportiert alle Kanäle des Wii U Sound Streams in mehrere Dateien anstatt diese in einer zu kombinieren." /* 165 */ , 
"Dekodiere Wii U Sound Stream in MP3(s)" /* 166 */ , 
"Dekodiere Wii U Sound Stream in MP3s" /* 167 */ , 
"Nur ein einziger Kanal kann in MP3 konvertiert werden. Möchtest du jeden Kanal einzeln konvertieren?" /* 168 */ , 
"Wii U Sound Streams|*.bfstm;*.bfwav" /* 169 */ , 
"WAV Audio-Dateien|*.wav|MP3 Audio-Dateien|*.mp3" /* 170 */ , 
"Wähle eine Sprache für Uwizard." /* 171 */ 
                },
#endregion
#region SPANISH_UWIZARD
            new string[] {
"Verificado exitosamente respecto al SHA1" /* 0 */ , 
"La verificación respecto al SHA1 ha fallado" /* 1 */ , 
"No se ha ingresado ninguna Key" /* 2 */ , 
"No hay un SHA1 disponible" /* 3 */ , 
"No se ha encontrado un archivo de configuración." /* 4 */ , 
"Secuencia Hexadecimal inválida" /* 5 */ , 
"Descargando" /* 6 */ , 
"Leyendo" /* 7 */ , 
"La imagen de disco de Wii U no es válida, recuerda descomprimirla primero" /* 8 */ , 
"Buscando en la base de datos de juegos" /* 9 */ , 
"Este juego no se ha encontrado en la base de datos. Por favor ingresa el nombre del juego:" /* 10 */ , 
"Ingresa el nombre del juego" /* 11 */ , 
"PAL: Europa" /* 12 */ , 
"NTSC: Japón" /* 13 */ , 
"PAL: Australia" /* 14 */ , 
"NTSC: Norteamericano" /* 15 */ , 
"Buscando portadas en gameTDB" /* 16 */ , 
"Juegos de Wii U|*.wud|Todos los archivos|*.*" /* 17 */ , 
"La key del juego de Wii U es necesaria para desencriptar los datos" /* 18 */ , 
"La common key es necesaria desencriptar los datos" /* 19 */ , 
"La key del juego en disco no es válida" /* 20 */ , 
"La common key no es válida" /* 21 */ , 
"Selecciona donde guardar los archivos extraídos" /* 22 */ , 
"Error al extraer contenidos" /* 23 */ , 
"versión " /* 24 */ , 
"Se ha actualizado Uwizard satisfactoriamente a la versión" /* 25 */ , 
"Se ha actualizado Uwizard a la versión, pero debido a un error es posible que tus datos se hayan modificado" /* 26 */ , 
"La lista de juegos ya está actualizada." /* 27 */ , 
"{0} juegos han sido añadidos {1} juegos han sido actualizados desde gametdb.com" /* 28 */ , 
"{0} juego agregado {1} juegos actualizados desde gametdb.com" /* 29 */ , 
"{0} juego agregado {1}juego actualizado desde gametdb.com" /* 30 */ , 
"{0} juego agregado {1}juego actualizado desde gametdb.com" /* 31 */ , 
"Ha ocurrido un error al descargar información de wiiubrew.net. Se ha cancela la actualización" /* 32 */ , 
"La versión del archivo en wiiubrew.net está corrupta!" /* 33 */ , 
"ERROR" /* 34 */ , 
"Hay una nueva versión de Uwizard disponible. Deseas actualizar desde la versión {0} a la {1} ?" /* 35 */ , 
"Uwizard está actualizado" /* 36 */ , 
"Realmente deseas eliminar todas las keys de forma permanente, incluyendo las keys de todos los títulos" /* 37 */ , 
"Se ha eliminado todas las claves (keys) satisfactoriamente" /* 38 */ , 
"Deseas eliminar la información de todos los juegos de forma permanente?" /* 39 */ , 
"Para hacer eso deberás viajar al futuro." /* 40 */ , 
"Desencriptando contenido" /* 41 */ , 
"Se ha terminado de desencriptar el contenido" /* 42 */ , 
"Error al desencriptar el contenido" /* 43 */ , 
"Abriendo ruta de salida" /* 44 */ , 
"Iniciando descarga desde NUS. Espera un momento por favor" /* 45 */ , 
"Descarga desde NUS finalizada." /* 46 */ , 
"La descarga ha fallado" /* 47 */ , 
"Puede que este archivo no sea un flujo de sonido válido de Wii U, o que el archivo esté siendo usado por otro programa" /* 48 */ , 
"Selecciona una carpeta donde buscar archivos de sonido" /* 49 */ , 
"No hay archivos de sonido compatibles en la carpeta seleccionada" /* 50 */ , 
"Error al convertir" /* 51 */ , 
"Selecciona una carpeta con juegos de Wii U para añadirlos a la lista" /* 52 */ , 
"No has guardado los ajustes en la información del juego de Wii U, es decir el nombre del y la key del título. ¿Deseas guardarlos ahora?" /* 53 */ , 
"La common Key es necesaria para desencriptar los datos" /* 54 */ , 
"Escribe el nombre del título a añadir" /* 55 */ , 
"Administrador de WUD" /* 56 */ , 
"NUS Downloader U" /* 57 */ , 
"Administrador de sonido" /* 58 */ , 
"Administrador de archivo" /* 59 */ , 
"Ajustes" /* 60 */ , 
"Mostrar lista de juegos" /* 61 */ , 
"Vaciar lista de carpetas" /* 62 */ , 
"Añadir directorio" /* 63 */ , 
"Limpiar juego de Wii U (reduce el tamaño del juego)" /* 64 */ , 
"Mostrar portada completa" /* 65 */ , 
"Guardar información del juego" /* 66 */ , 
"Extraer archivos del juego." /* 67 */ , 
"Información del juego" /* 68 */ , 
"Key del título" /* 69 */ , 
"Importar" /* 70 */ , 
"Nombre del juego" /* 71 */ , 
"ID del juego" /* 72 */ , 
"Abrir juego de Wii U" /* 73 */ , 
"Limpiar lista" /* 74 */ , 
"Eliminar título" /* 75 */ , 
"Añadir título" /* 76 */ , 
"Versión:" /* 77 */ , 
"ID del título:" /* 78 */ , 
"Desencriptar contenido" /* 79 */ , 
"Abrir carpeta" /* 80 */ , 
"Reproducir transmisión de sonido" /* 81 */ , 
"Seleccionar carpeta" /* 82 */ , 
"Archivos de sonido en la carpeta seleccionada" /* 83 */ , 
"Desencriptar flujo de sonido de Wii U" /* 84 */ , 
"Decodificar flujo de sonido de Wii U en un archivo de sonido .WAV" /* 85 */ , 
"Decodificar flujos de sonido de Wii U en un archivos de sonido .WAV" /* 86 */ , 
"Muy pronto." /* 87 */ , 
"Empaquetar y comprimir SARC.SZS" /* 88 */ , 
"Descomprimir y extraer SARC.SZS" /* 89 */ , 
"Empaquetar SARC" /* 90 */ , 
"Extraer SARC" /* 91 */ , 
"Comprimir SZS" /* 92 */ , 
"Descomprimir SZS" /* 93 */ , 
"Ocular keys" /* 94 */ , 
"Importar base de datos de juegos" /* 95 */ , 
"Eliminar todas las key de juegos" /* 96 */ , 
"Eliminar base de datos de juegos" /* 97 */ , 
"Ancast Key de Starbuck de Wii U" /* 98 */ , 
"Importar key" /* 99 */ , 
"Ancast Key de Expresso de Wii U" /* 100 */ , 
"Acerca de Uwizard" /* 101 */ , 
"Common Key de Wii U" /* 102 */ , 
"Buscar actualizaciones" /* 103 */ , 
"Comenzar descarga" /* 104 */ , 
"Detener descarga" /* 105 */ , 
"Elimina las direcciones mostradas arriba en la lista. Los juegos en sí no son eliminados" /* 106 */ , 
"Añade una carpeta a la lista de arriba. Los juegos de Wii U contenidos en esa carpeta se añaden a la lista" /* 107 */ , 
"Reemplaza por ceros los espacios sin información. Esto permite reducir el tamaño del backup usando compresión NTFS nativa" /* 108 */ , 
"Guarda todos los cambios hechos a la información de los juegos (por ejemplo poner la key del título) permanentemente" /* 109 */ , 
"Elimina todos los títulos de la lista de acceso rápido" /* 110 */ , 
"Elimina el título seleccionado de la lista de acceso rápido" /* 111 */ , 
"Agrega el título recién ingresado y su versión a la lista de acceso rápido" /* 112 */ , 
"Esta lista proporciona una forma ágil de escoger títulos NUS para descargar" /* 113 */ , 
"Versión del título NUS. Si dejas este campo en blanco, se descargará la última versión disponible" /* 114 */ , 
"ID del título NUS. DEBE tener 16 caracteres de longitud" /* 115 */ , 
"Compila todos los archivos dentro de una carpeta en un archivo SARC, luego comprime el archivo con Yaz0" /* 116 */ , 
"Descomprime el archivo Yaz0, si el archivo comprimido es un archivo SARC extrae todo su contenido" /* 117 */ , 
"Compile los archivos contenidos dentro de una carpeta en un archivo SARC" /* 118 */ , 
"Extrae todos los archivos contenidos en un archivo SARC" /* 119 */ , 
"Comprime un archivo con Yaz0" /* 120 */ , 
"Descomprime un archivo Yaz0" /* 121 */ , 
"Oculta todas las keys que son propiedad de Nintendo de los recuadros no activos." /* 122 */ , 
"Elimina de forma permanente las Keys propietarias de Nintendo, incluyendo las keys de títulos" /* 123 */ , 
"Elimina de forma permanente la información de todos los juegos" /* 124 */ , 
"Ok" /* 125 */ , 
"Copyright 2015 Mysteriosoft" /* 126 */ , 
"Alojado en wiiubrew.net" /* 127 */ , 
"Se requiere un ticket para desencriptar la información contenida, pero el ticket necesario no está disponible en los servidores de Nintendo. Deseas seleccionar manualmente el ticket a usar? Para un juego (de disco) de Wii U, el ticket está contenido en el directorio \"system\\02\\title.tik\"." /* 128 */ , 
"Si" /* 129 */ , 
"No" /* 130 */ , 
"Descargando título {0} v{1}... {2} [Último]" /* 131 */ , 
"Almacenando contenido encriptado" /* 132 */ , 
"Descargando TMD…" /* 133 */ , 
"La descarga de TMD ha fallado" /* 134 */ , 
"Verificando TMD…" /* 135 */ , 
"Versión del título" /* 136 */ , 
"{0} Contenidos" /* 137 */ , 
"{0} Archivos, {1} bytes" /* 138 */ , 
"Descargando Ticket:" /* 139 */ , 
"Ha fallado la descarga del Ticket:" /* 140 */ , 
"Comprobando validez del Ticket…" /* 141 */ , 
"Ticket no disponible" /* 142 */ , 
"Descargar contenido #{0} de {1}... ({2} bytes) para" /* 143 */ , 
"Usando archivo local, omitiendo" /* 144 */ , 
"Se ha detenido el proceso de descarga" /* 145 */ , 
"Descarga del contenido #{0} de {1} ha fallado..." /* 146 */ , 
"Creditos:\r\n  Mr. Mysterio - Programador de Uwizard\r\n  Crediar - Programador de DiscU and CDecrypt\r\n  MasterF0x - Distribuidor del decodificador BFSTM\r\n  GameTDB - Portadas de juegos\r\n  VinsCool, capito27, Phanteon, send0r - Traduciones\r\n\r\nChangeLog:\r\n  v1.1.3\r\n    Idioma Español añadió.\r\n    Lengua Alemana añadió.\r\n    \r\n\r\n  v1.1.2\r\n    Se añade decodificador de BFWAV.\r\n    Se incorpora compilador de MP3.\r\n\r\n  v1.1.1\r\n    Se agrega administrador de archivos SZS y SARC.\r\n    Selección multiple de BFSTM y se paración opcional en canales.\r\n    Se añade Interface de linea de comandos.\r\n    Mas títulos NUS agregados a la lista de acceso rápido.\r\n    corrección de fallos.\r\n\r\n  v1.1.0\r\n    NUS Downloader U agregado.\r\n    Se agrega decodificador de BFSTM.\r\n    Lista para selecion de juegos de Wii U agregada.\r\n    Corrección de fallos menores.\r\n\r\n  v1.0.1\r\n    Se añade la opción para ocultar las Keys.\r\n    Corrección de fallos menores.\r\n\r\n  v1.0.0\r\n    Creación del programa." /* 147 */ , 
"Exportar base de datos de juegos" /* 148 */ , 
"Esta base de datos de juegos fue creada con una versión más reciente de Uwizard. Puede ser incompatible" /* 149 */ , 
"Binarios y archivos de texto|*.bin;*.txt" /* 150 */ , 
"Archivos de texto|*.txt|Todos los archivos|*.*" /* 151 */ , 
"Todos los archivos|*.*" /* 152 */ , 
"Convertir flujo de sonido de Wii U en archivos WAV" /* 153 */ , 
"Excepción:" /* 154 */ , 
"Archivos SARC|*.sarc|Todos los archivos|*.*" /* 155 */ , 
"Error al extraer el archivo SARC" /* 156 */ , 
"Selecciona la carpeta que se va a empaquetar en un archivo SARC" /* 157 */ , 
"Error al empaquetar en archivo SARC" /* 158 */ , 
"Archivos Yaz0 comprimidos |*.szs|Todos los archivos|*.*" /* 159 */ , 
"Este archivo no es un Yaz0 comprimido" /* 160 */ , 
"Error al descomprimir archivo SZS" /* 161 */ , 
"Error al comprimir archivo SZS" /* 162 */ , 
"Selecciona una carpeta para comprimir en un archivo SARC.SZS" /* 163 */ , 
"Exportar canales de forma separada" /* 164 */ , 
"Exporta los canales de un archivo de flujo de sonido de Wii U en archivos separados, en vez de unirlos en uno solo" /* 165 */ , 
"Decodificar un archivo de flujo de sonido de Wii U en archivos MP3" /* 166 */ , 
"Decodificar archivos de flujo de sonido de Wii U en archivos MP3" /* 167 */ , 
"Solo puede convertirse los canales de manera individual (en MP3). Deseas convertir cada canal de forma independiente?" /* 168 */ , 
"Archivos de flujo de sonido de Wii U|*.bfstm;*.bfwav" /* 169 */ , 
"Archivos de sonido WAV|*.wav|Archivos de sonido MP3|*.mp4" /* 170 */ , 
"Seleccione un idioma para Uwizard." /* 171 */ 
                }
#endregion
#region ITALIAN_UWIZARD
		new string[] { // Italian
"Verificato corretto dallo SHA1" /* 0 */ , 
"Verificato incorretto dallo SHA1" /* 1 */ , 
"Nessuna chiave inserita" /* 2 */ , 
"Nessuno SHA1 disponibile" /* 3 */ , 
"Manca il file delle impostazioni! Le tue impostazioni e chiavi di sistema sono state perdute." /* 4 */ , 
"Stringa Hex invalida" /* 5 */ , 
"In download " /* 6 */ , 
"In lettura " /* 7 */ , 
"Immagine disco Wii U non valida. Forse hai dimenticato di estrarre il file?" /* 8 */ , 
"Ricerca nel database di giochi..." /* 9 */ , 
"Questo gioco non è nel database. Inserire il nome:" /* 10 */ , 
"Inserire il nome del gioco" /* 11 */ , 
"PAL: Europa" /* 12 */ , 
"NTSC: Giappone" /* 13 */ , 
"PAL: Australia" /* 14 */ , 
"NTSC: Nord America" /* 15 */ , 
"Ricerca cover in GameTDB..." /* 16 */ , 
"Giochi Wii U|*.wud|All Files|*.*" /* 17 */ , 
"La title key del disco è necessaria per decriptare i dati." /* 18 */ , 
"La common key è necessaria per decriptare i dati." /* 19 */ , 
"La title key del disco non è valida." /* 20 */ , 
"La common key non è valida." /* 21 */ , 
"Selezionare dove estrarre i file." /* 22 */ , 
"Errore estrazione file!" /* 23 */ , 
"versione " /* 24 */ , 
"Uwizard è stato aggiornato con successo alla versione " /* 25 */ , 
"Uwizard è stato aggiornato alla versione {0}, ma a causa di un errore nell'aggiornamento, alcuni dei tuoidati potrebbero non essere intatti." /* 26 */ , 
"La lista dei giochi è aggiornata." /* 27 */ , 
"{0} giochi aggiunti e {1} giochi aggiornati da gametdb.com" /* 28 */ , 
"{0} gioco aggiunto e {1} giochi aggiornati da gametdb.com" /* 29 */ , 
"{0} giochi aggiunti e {1} gioco aggiornato da gametdb.com" /* 30 */ , 
"{0} gioco aggiunto {1} gioco aggiornato da gametdb.com" /* 31 */ , 
"Errore download informazioni versione da wiiubrew.net. Aggiornamento annullato." /* 32 */ , 
"Versione corrotta del file in wiiubrew.net!" /* 33 */ , 
"ERRORE" /* 34 */ , 
"Nuova versione di Uwizard disponibile. Aggiornare da {0} a {1}?" /* 35 */ , 
"Uwizard è aggiornato!" /* 36 */ , 
"Sicuro di voler cancellare definitivamente tutte le chiavi incluse le title key?" /* 37 */ , 
"Tutte le chiavi cancellate con successo!" /* 38 */ , 
"Sicuro di voler cancellare tutte le informazioni su tutti i giochi?" /* 39 */ , 
"Devi viaggiare nel futuro per usare questa funzione! :)" /* 40 */ , 
"Decriptazione dei contenuti..." /* 41 */ , 
"Decriptazione dei contenuti terminata." /* 42 */ , 
"Errore decriptazione contenuti!" /* 43 */ , 
"Apertura cartella di destinazione..." /* 44 */ , 
"Avvio download NUS. Si prega di attendere!" /* 45 */ , 
"Download NUS concluso." /* 46 */ , 
"Download fallito: " /* 47 */ , 
"O questo file non è un flusso audio Wii U valido, o il file è in uso da un altro programma." /* 48 */ , 
"Selezionare dove cercare i file audio." /* 49 */ , 
"Non ci sono file audio compatibili nella cartella selezionata!" /* 50 */ , 
"Errore conversione " /* 51 */ , 
"Selezionare una cartella che contiene i giochi Wii U da aggiungere a questa lista." /* 52 */ , 
"Non hai salvato i tuoi cambiamenti alle informazioni sul gioco Wii U attuale. Questo include il nome e la title key. Salvare questi cambiamenti adesso?" /* 53 */ , 
"La common key è necessaria per decriptare i dati." /* 54 */ , 
"Scrivi il nome del titolo da aggiungere." /* 55 */ , 
"Gestore WUD" /* 56 */ , 
"NUS Downloader U" /* 57 */ , 
"Gestore audio" /* 58 */ , 
"Gestore archivi" /* 59 */ , 
"Impostazioni" /* 60 */ , 
"Mostra lista dei giochi" /* 61 */ , 
"Cancella lista cartelle" /* 62 */ , 
"Aggiungi cartella" /* 63 */ , 
"Ripulisci gioco Wii U" /* 64 */ , 
"Mostra copertina completa" /* 65 */ , 
"Informazioni salvataggio" /* 66 */ , 
"Estrai file del gioco" /* 67 */ , 
"Info gioco" /* 68 */ , 
"Title Key" /* 69 */ , 
"Importa" /* 70 */ , 
"Nome gioco" /* 71 */ , 
"ID gioco" /* 72 */ , 
"Apri gioco Wii U" /* 73 */ , 
"Pulisci lista" /* 74 */ , 
"Cancella titolo" /* 75 */ , 
"Aggiungi titolo" /* 76 */ , 
"Versione:" /* 77 */ , 
"ID titolo:" /* 78 */ , 
"Decripta contenuti" /* 79 */ , 
"Apri cartella" /* 80 */ , 
"Riproduci flusso audio" /* 81 */ , 
"Seleziona cartella" /* 82 */ , 
"File audio nella cartella selezionata" /* 83 */ , 
"Decodifica un flusso audio Wii U" /* 84 */ , 
"Decodifica dei flussi audio Wii U in WAV" /* 85 */ , 
"Decodifica un flusso audio Wii U in WAV" /* 86 */ , 
"Prossimamente!" /* 87 */ , 
"Impacchetta e comprimi SARC.SZS" /* 88 */ , 
"Decomprimi ed estrai SARC.SZS" /* 89 */ , 
"Impachetta SARC" /* 90 */ , 
"Estrai SARC" /* 91 */ , 
"Comprimi SZS" /* 92 */ , 
"Decomprimi SZS" /* 93 */ , 
"Nascondi chiavi" /* 94 */ , 
"Importa database giochi" /* 95 */ , 
"Cancella tutte le chiavi" /* 96 */ , 
"Cancella database gioch" /* 97 */ , 
"Chiave ancast del Wii U Starbuck" /* 98 */ , 
"Importa chiave" /* 99 */ , 
"Chiave ancast Wii U Espresso" /* 100 */ , 
"Riguardo a Uwizard" /* 101 */ , 
"Common key Wii U" /* 102 */ , 
"Controlla aggiornamenti" /* 103 */ , 
"Avvia download" /* 104 */ , 
"Interrompi download" /* 105 */ , 
"Questo rimuoverà tutte le directory dalla lista qui sopra. I giochi stessi non verranno eliminati." /* 106 */ , 
"Aggiunge una cartella alla lista qui sopra. Tutti i giochi Wii U dentro quella cartella verranno mostrati nella lista qui sopra." /* 107 */ , 
"Azzera i dati inutilizzati. Questo permette di comprimere il backup più efficientemente utilizzando la compressione nativa NTFS. " /* 108 */ , 
"Salva tutte le modifiche alle informazioni del gioco (come l'inserimento della title key) su un registro permanente." /* 109 */ , 
"Cancella tutti i titoli dalla lista di accesso rapido." /* 110 */ , 
"Cancella il titolo selezionato dalla lista di accesso rapido." /* 111 */ , 
"Aggiunge il titolo e la versione attualmente inseriti alla lista di accesso rapido." /* 112 */ , 
"Questa lista fornisce un modo facile di scegliere i titoli NUS da scaricare." /* 113 */ , 
"Versione titolo NUS. Se lasciato vuoto, verrà scaricata l'ultima versione." /* 114 */ , 
"ID titolo NUS. DEVE essere lungo 16 caratteri." /* 115 */ , 
"Compila tutti i file dentro una cartella in un archivio SARC, poi comprime l'archivio con Yaz0." /* 116 */ , 
"Decomprime un file Yaz0 e, se il file compress è un archivio SARC, allora estrae tutti i file all'interno dell'archivio." /* 117 */ , 
"Compila tutti i file dentro una cartella in un archivio SARC." /* 118 */ , 
"Estrae tutti i file dentro un archivio SARC." /* 119 */ , 
"Comprime un file con Yaz0." /* 120 */ , 
"Decomprime un file Yaz0." /* 121 */ , 
"Nasconde tutte le chiavi proprietarie di Nintendo dalle caselle inattive." /* 122 */ , 
"Cancella definitivamente tutte le chiavi proprietarie Nintendo incluse le title key." /* 123 */ , 
"Cancella tutte le informazioni su tutti i giochi." /* 124 */ , 
"OK" /* 125 */ , 
"Copyright 2015 Mysteriosoft" /* 126 */ , 
"Ospitato in wiiubrew.net" /* 127 */ , 
"È necessario un ticket per decriptare i contenuti, ma un ticket per questo titolo non è disponibile nel server di Nintendo. Selezionare un file ticket da usare? Il ticket in un disco di gioco Wii U per lo stesso gioco si trova in \"system\\02\\title.tik\"." /* 128 */ , 
"Sì" /* 129 */ , 
"No" /* 130 */ , 
"Scaricamento title {0} v{1}... {2} [Ultima]" /* 131 */ , 
"Salvataggio contenuti criptati..." /* 132 */ , 
"Scaricamento TMD..." /* 133 */ , 
"Scaricamento TMD fallito: " /* 134 */ , 
"Analisi TMD..." /* 135 */ , 
"Versione titolo: " /* 136 */ , 
"{0} contenuti" /* 137 */ , 
"{0} file, {1} byte" /* 138 */ , 
"Scaricamento ticket..." /* 139 */ , 
"Scaricamento ticket fallito: " /* 140 */ , 
"Analisi ticket..." /* 141 */ , 
"Ticket non disponibile" /* 142 */ , 
"Scaricamento contenuto #{0} di {1}... ({2} byte) su " /* 143 */ , 
"Usando file locale, saltato..." /* 144 */ , 
"L'operazione di scaricamento è stata annullata." /* 145 */ , 
"Scaricamento del contenuto #{0} di {1} fallito..." /* 146 */ , 
"Crediti:\r\n  Mr. Mysterio - Programmatore di Uwizard\r\n  Crediar - Programmatore di DiscU e CDecrypt\r\n  MasterF0x - Distributore di BFSTM Decoder\r\n  GameTDB - Copertine dei giochi\r\n  VinsCool, capito27, phanteon, send0r, nastys - Traduzione\r\n\r\nCambiamenti:\r\n  v1.1.3\r\n    Aggiunta lingua tedesca. \r\n    Aggiunta lingua spagnola.\r\n    Risolti bug minori.\r\n\r\n  v1.1.2\r\n    Aggiunto decodificatore BFWAV.\r\n    Aggiunto compilatore MP3.\r\n\r\n  v1.1.1\r\n    Aggiunta gestione archivi SZS e SARC.\r\n    Aggiunte selezione multipla e separazione opzionale canali BFSTM.\r\n    Aggiunta interfaccia a riga di comando.\r\n    Aggiunti altri titoli NUS alla lista di accesso rapido.\r\n    Risolti bug minori.\r\n    \r\n  v1.1.0\r\n    Aggiunto NUS Downloader U.\r\n    Aggiunto decodificatore BFSTM.\r\n    Aggiunta selezione lista giochi Wii U.\r\n    Risolti bug minori.\r\n    \r\n  v1.0.1\r\n    Aggiunta opzione per nascondere le chiavi.\r\n    Risolti bug minori.\r\n\r\n  v1.0.0\r\n    Creazione del programma" /* 147 */ , 
"Esporta database dei giochi" /* 148 */ , 
"Questo database dei giochi è stato generato da una nuova versione di Uwizard. Potrebbe essere incompatibile." /* 149 */ , 
"File binari e di testo|*.bin;*.txt" /* 150 */ , 
"File di testo|*.txt|Tutti i file|*.*" /* 151 */ , 
"Tutti i file|*.*" /* 152 */ , 
"Decodifica flusso audio in WAV" /* 153 */ , 
"Eccezione:" /* 154 */ , 
"Archivi SARC|*.sarc|Tutti i file|*.*" /* 155 */ , 
"Errore durante l'estrazione dell'archivio SARC!" /* 156 */ , 
"Selezionare una cartella da impacchettare in archivio SARC." /* 157 */ , 
"Errore impacchettamento archivio SARC!" /* 158 */ , 
"File compressi Yaz0|*.szs|Tutti i file|*.*" /* 159 */ , 
"Questo file non è compresso in Yaz0!" /* 160 */ , 
"Errore decompressione file SZS!" /* 161 */ , 
"Errore compressione file SZS!" /* 162 */ , 
"Selezionare una cartella da comprimere in un archivio compresso SARC.SZS." /* 163 */ , 
"Esporta canali separatamente" /* 164 */ , 
"Esporta tutti i canali da un flusso audio Wii U a file multipli invece di mischiarli in uno." /* 165 */ , 
"Decodifica flusso audio Wii U in MP3" /* 166 */ , 
"Decodifica flussi audio Wii U in MP3" /* 167 */ , 
"Solo ciascun canale individuale può essere convertito in MP3. Convertire i canali separatamente?" /* 168 */ , 
"Flussi audio Wii U|*.bfstm;*.bfwav" /* 169 */ , 
"File audio WAV|*.wav|File audio MP3|*.mp3" /* 170 */ , 
"Selezionare una lingua per Uwizard." /* 171 */ 
},
#endregion
        };
        public static void loadlang(Uwizard.Form1 userform) {
            userform.sha1_correct = userform.uwiz_langtext[0];
            userform.sha1_incorrect = userform.uwiz_langtext[1];
            userform.sha1_nokey = userform.uwiz_langtext[2];
            userform.sha1_nosha1 = userform.uwiz_langtext[3];
            userform.sha1_nosha1 = userform.uwiz_langtext[3];
            userform.page_wudmanager.Text = userform.uwiz_langtext[56];
            userform.showfold.Text = userform.uwiz_langtext[61];
            userform.wudlist_clearfolers.Text = userform.uwiz_langtext[62];
            userform.wudlist_addfolder.Text = userform.uwiz_langtext[63];
            userform.button13.Text = userform.uwiz_langtext[64];
            userform.show3d.Text = userform.uwiz_langtext[65];
            userform.button9.Text = userform.uwiz_langtext[66];
            userform.button8.Text = userform.uwiz_langtext[67];
            userform.groupBox8.Text = userform.uwiz_langtext[68];
            userform.groupBox7.Text = userform.uwiz_langtext[69];
            userform.gtkey_sha1status.Text = userform.uwiz_langtext[2];
            userform.button7.Text = userform.uwiz_langtext[70];
            userform.groupBox6.Text = userform.uwiz_langtext[71];
            userform.groupBox5.Text = userform.uwiz_langtext[72];
            userform.button6.Text = userform.uwiz_langtext[73];
            userform.page_nus.Text = userform.uwiz_langtext[57];
            userform.nus_clearlist.Text = userform.uwiz_langtext[74];
            userform.nus_deletefromlist.Text = userform.uwiz_langtext[75];
            userform.nus_add2list.Text = userform.uwiz_langtext[76];
            userform.label2.Text = userform.uwiz_langtext[77];
            userform.label1.Text = userform.uwiz_langtext[78];
            userform.nus_usecdecrypt.Text = userform.uwiz_langtext[79];
            userform.nus_startdownload.Text = userform.uwiz_langtext[104];
            userform.page_bfstmmanager.Text = userform.uwiz_langtext[58];
            userform.bfstm_openfolder.Text = userform.uwiz_langtext[80];
            userform.bfstm_convertbfstm2wav.Text = userform.uwiz_langtext[86];
            userform.bfstm_convert1fromlisttomp3.Text = userform.uwiz_langtext[166];
            userform.bfstm_play.Text = userform.uwiz_langtext[81];
            userform.button16.Text = userform.uwiz_langtext[82];
            userform.groupBox3.Text = userform.uwiz_langtext[83];
            userform.bfstm_convertbfstm2wav_notlist.Text = userform.uwiz_langtext[84];
            userform.page_szsmanager.Text = userform.uwiz_langtext[59];
            userform.arc_pac_com_sarcszs.Text = userform.uwiz_langtext[88];
            userform.arc_dec_ex_sarcszs.Text = userform.uwiz_langtext[89];
            userform.arc_createsarc.Text = userform.uwiz_langtext[90];
            userform.arc_extractsarc.Text = userform.uwiz_langtext[91];
            userform.arc_createszs.Text = userform.uwiz_langtext[92];
            userform.arc_extractszs.Text = userform.uwiz_langtext[93];
            userform.page_settings.Text = userform.uwiz_langtext[60];
            userform.imptitlekeys.Text = userform.uwiz_langtext[95];
            userform.hideKeys.Text = userform.uwiz_langtext[94];
            userform.exptitlekeys.Text = userform.uwiz_langtext[148];
            userform.button11.Text = userform.uwiz_langtext[96];
            userform.button10.Text = userform.uwiz_langtext[97];
            userform.groupBox4.Text = userform.uwiz_langtext[98];
            userform.button5.Text = userform.uwiz_langtext[99];
            //userform.askey_sha1status.Text = userform.uwiz_langtext[2];
            userform.groupBox1.Text = userform.uwiz_langtext[100];
            userform.button4.Text = userform.uwiz_langtext[99];
            //userform.aekey_sha1status.Text = userform.uwiz_langtext[2];
            userform.button2.Text = userform.uwiz_langtext[101];
            userform.groupBox2.Text = userform.uwiz_langtext[102];
            userform.button3.Text = userform.uwiz_langtext[99];
            //userform.ckey_sha1status.Text = userform.uwiz_langtext[2];
            userform.button1.Text = userform.uwiz_langtext[103];
            //userform = userform.uwiz_langtext[];
            userform.bfstm_exchans.Text = userform.uwiz_langtext[164];
            userform.vertext.Text = userform.uwiz_langtext[24] + Form1.getVerText(Form1.myversion);

            userform.toolTip1.SetToolTip(userform.wudlist_clearfolers, userform.uwiz_langtext[106]);
            userform.toolTip1.SetToolTip(userform.wudlist_addfolder, userform.uwiz_langtext[107]);
            userform.toolTip1.SetToolTip(userform.button13, userform.uwiz_langtext[108]);
            userform.toolTip1.SetToolTip(userform.button9, userform.uwiz_langtext[109]);
            userform.toolTip1.SetToolTip(userform.nus_clearlist, userform.uwiz_langtext[110]);
            userform.toolTip1.SetToolTip(userform.nus_deletefromlist, userform.uwiz_langtext[111]);
            userform.toolTip1.SetToolTip(userform.nus_add2list, userform.uwiz_langtext[112]);
            userform.toolTip1.SetToolTip(userform.nus_dlist, userform.uwiz_langtext[113]);
            userform.toolTip1.SetToolTip(userform.nus_titlever, userform.uwiz_langtext[114]);
            userform.toolTip1.SetToolTip(userform.nus_titleid, userform.uwiz_langtext[115]);
            userform.toolTip1.SetToolTip(userform.arc_pac_com_sarcszs, userform.uwiz_langtext[116]);
            userform.toolTip1.SetToolTip(userform.arc_dec_ex_sarcszs, userform.uwiz_langtext[117]);
            userform.toolTip1.SetToolTip(userform.arc_createsarc, userform.uwiz_langtext[118]);
            userform.toolTip1.SetToolTip(userform.arc_extractsarc, userform.uwiz_langtext[119]);
            userform.toolTip1.SetToolTip(userform.arc_createszs, userform.uwiz_langtext[120]);
            userform.toolTip1.SetToolTip(userform.arc_extractszs, userform.uwiz_langtext[121]);
            userform.toolTip1.SetToolTip(userform.hideKeys, userform.uwiz_langtext[122]);
            userform.toolTip1.SetToolTip(userform.button11, userform.uwiz_langtext[123]);
            userform.toolTip1.SetToolTip(userform.button10, userform.uwiz_langtext[124]);
            userform.toolTip1.SetToolTip(userform.bfstm_exchans, userform.uwiz_langtext[165]);
            /*userform.toolTip1.SetToolTip(userform, userform.uwiz_langtext[106]);
            userform.toolTip1.SetToolTip(userform, userform.uwiz_langtext[106]);
            userform.toolTip1.SetToolTip(userform, userform.uwiz_langtext[106]);//*/
        }
    }
}
