//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uwizard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uwizard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] bfstm_decoder {
            get {
                object obj = ResourceManager.GetObject("bfstm_decoder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CDecrypt {
            get {
                object obj = ResourceManager.GetObject("CDecrypt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dbutton {
            get {
                object obj = ResourceManager.GetObject("dbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] DiscU {
            get {
                object obj = ResourceManager.GetObject("DiscU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GameTDB {
            get {
                object obj = ResourceManager.GetObject("GameTDB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] libeay32 {
            get {
                object obj = ResourceManager.GetObject("libeay32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] libg7221_decode {
            get {
                object obj = ResourceManager.GetObject("libg7221_decode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] libmpg123_0 {
            get {
                object obj = ResourceManager.GetObject("libmpg123_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] libvorbis {
            get {
                object obj = ResourceManager.GetObject("libvorbis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MMA4 {
            get {
                object obj = ResourceManager.GetObject("MMA4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] mp3enc {
            get {
                object obj = ResourceManager.GetObject("mp3enc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] unzip {
            get {
                object obj = ResourceManager.GetObject("unzip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Updater {
            get {
                object obj = ResourceManager.GetObject("Updater", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] yaz0dec {
            get {
                object obj = ResourceManager.GetObject("yaz0dec", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] yaz0enc {
            get {
                object obj = ResourceManager.GetObject("yaz0enc", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
